version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-server-db
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - POSTGRES_DB=postgres
      

  stats-server:
    build: ./stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
        - "9090:9090"
    depends_on:
        - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=iamroot

 ewm-service:
   ports:
     - "8080:8080"

 ewm-db:
   image: postgres:14-alpine
